"""Generate an AcroForm-enabled invoice.pdf template.

Each form field's `Name` will be used as the key in PdfTemplate#render(name, fields, out).
"""
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import mm

OUT = "molly-document-example/src/main/resources/templates/pdf/invoice.pdf"

W, H = A4
c = canvas.Canvas(OUT, pagesize=A4)
form = c.acroForm

# ---- 标题 ----
c.setFont("Helvetica-Bold", 22)
c.drawCentredString(W / 2, H - 28 * mm, "INVOICE")

c.setFont("Helvetica", 10)
c.drawString(20 * mm, H - 40 * mm, "Molly Document Starter - AcroForm Template Demo")

# ---- 顶部：编号 / 日期 ----
def label(x, y, text):
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x, y, text)

label(20 * mm, H - 55 * mm, "Invoice No.")
form.textfield(
    name="invoiceNo", tooltip="发票号",
    x=45 * mm, y=H - 58 * mm, width=60 * mm, height=6 * mm,
    borderColor=colors.grey, fillColor=colors.whitesmoke,
    textColor=colors.black, forceBorder=True,
)

label(120 * mm, H - 55 * mm, "Date")
form.textfield(
    name="issueDate", tooltip="开票日期",
    x=135 * mm, y=H - 58 * mm, width=55 * mm, height=6 * mm,
    borderColor=colors.grey, fillColor=colors.whitesmoke,
    forceBorder=True,
)

# ---- 客户信息 ----
label(20 * mm, H - 75 * mm, "Customer")
form.textfield(
    name="customer", tooltip="客户名称",
    x=45 * mm, y=H - 78 * mm, width=145 * mm, height=6 * mm,
    forceBorder=True, borderColor=colors.grey,
)

label(20 * mm, H - 90 * mm, "Phone")
form.textfield(
    name="phone", tooltip="联系电话",
    x=45 * mm, y=H - 93 * mm, width=60 * mm, height=6 * mm,
    forceBorder=True, borderColor=colors.grey,
)

label(120 * mm, H - 90 * mm, "Email")
form.textfield(
    name="email", tooltip="邮箱",
    x=135 * mm, y=H - 93 * mm, width=55 * mm, height=6 * mm,
    forceBorder=True, borderColor=colors.grey,
)

label(20 * mm, H - 105 * mm, "Address")
form.textfield(
    name="address", tooltip="地址",
    x=45 * mm, y=H - 108 * mm, width=145 * mm, height=6 * mm,
    forceBorder=True, borderColor=colors.grey,
)

# ---- 明细表头 ----
y0 = H - 130 * mm
c.setFillColor(colors.HexColor("#1f77b4"))
c.rect(20 * mm, y0, 170 * mm, 8 * mm, fill=1, stroke=0)
c.setFillColor(colors.white)
c.setFont("Helvetica-Bold", 10)
c.drawString(22 * mm, y0 + 2.5 * mm, "Item")
c.drawString(95 * mm, y0 + 2.5 * mm, "Qty")
c.drawString(120 * mm, y0 + 2.5 * mm, "Unit Price")
c.drawString(160 * mm, y0 + 2.5 * mm, "Amount")
c.setFillColor(colors.black)

# ---- 明细 3 行（字段名 item1Name/item1Qty/item1Price/item1Amount ...）----
row_h = 9 * mm
for i in range(1, 4):
    y = y0 - i * row_h
    c.setStrokeColor(colors.lightgrey)
    c.line(20 * mm, y, 190 * mm, y)
    form.textfield(
        name=f"item{i}Name", x=22 * mm, y=y + 1 * mm, width=70 * mm, height=6 * mm,
        borderColor=colors.white, forceBorder=False,
    )
    form.textfield(
        name=f"item{i}Qty", x=95 * mm, y=y + 1 * mm, width=20 * mm, height=6 * mm,
        borderColor=colors.white, forceBorder=False,
    )
    form.textfield(
        name=f"item{i}Price", x=120 * mm, y=y + 1 * mm, width=35 * mm, height=6 * mm,
        borderColor=colors.white, forceBorder=False,
    )
    form.textfield(
        name=f"item{i}Amount", x=160 * mm, y=y + 1 * mm, width=28 * mm, height=6 * mm,
        borderColor=colors.white, forceBorder=False,
    )

# ---- 合计 ----
ytotal = y0 - 4 * row_h
c.setFont("Helvetica-Bold", 10)
c.drawString(120 * mm, ytotal + 2 * mm, "Subtotal")
form.textfield(name="subtotal", x=160 * mm, y=ytotal + 1 * mm, width=28 * mm, height=6 * mm, forceBorder=True, borderColor=colors.grey)

c.drawString(120 * mm, ytotal - 8 * mm + 2 * mm, "Tax")
form.textfield(name="tax", x=160 * mm, y=ytotal - 8 * mm + 1 * mm, width=28 * mm, height=6 * mm, forceBorder=True, borderColor=colors.grey)

c.drawString(120 * mm, ytotal - 16 * mm + 2 * mm, "Total")
form.textfield(name="total", x=160 * mm, y=ytotal - 16 * mm + 1 * mm, width=28 * mm, height=6 * mm, forceBorder=True, borderColor=colors.black)

# ---- 备注 ----
label(20 * mm, 50 * mm, "Remark")
form.textfield(
    name="remark", tooltip="备注",
    x=45 * mm, y=30 * mm, width=145 * mm, height=20 * mm,
    fieldFlags="multiline", forceBorder=True, borderColor=colors.grey,
)

# ---- 签章 ----
c.setFont("Helvetica-Oblique", 9)
c.setFillColor(colors.grey)
c.drawRightString(190 * mm, 15 * mm, "-- Generated by molly-document-spring-boot-starter --")

c.save()
print(f"wrote {OUT}")
